import Head from "next/head";
import TitleBar from "@/components/titleBar/TitleBar";
import CardContainer from "@/components/cardContainer/CardContainer";
// import TitleBar from "./components/titleBar/TitleBar";
// import CardContainer from "./components/cardContainer/cardContainer";
import styles from "@/styles/pageStyles/Home.module.scss";

export const getStaticProps = async (context) => {
  const baseUrl = "https://restcountries.com/v2/all";
  // const url = createUrl(baseUrl, {
  //   fields: ["name", "population", "region", "capital", "flags"],
  // });
  // const data = fetchApiData(url);

  const response = await fetch(
    "https://restcountries.com/v2/all?fields=name%2Cpopulation%2Cregion%2Ccapital%2Cflags"
  );
  const data = await response.json();

  return { props: { data } };
};

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TitleBar />
        <CardContainer data={data} />
      </main>
    </>
  );
}
