import Head from "next/head";
import TitleBar from "@/components/titleBar/TitleBar";
import CardContainer from "@/components/cardContainer/CardContainer";
import { createUrl } from "@/functions/createUrl";
import styles from "@/styles/pageStyles/Home.module.scss";
import { useContext, useEffect } from "react";
import {
  AllCountryContext,
  AllCountryContextProvider,
} from "@/contexts/AllCountryContext";

export const getStaticProps = async () => {
  const url = createUrl("all", {
    fields: ["name", "population", "region", "capital", "flags"],
  });

  const response = await fetch(url);
  const data = await response.json();

  return { props: { data } };
};

export default function Home({ data }) {
  const [allCountryData, setAllCountryData] = useContext(AllCountryContext);

  useEffect(() => {
    setAllCountryData(data);
  }, []);

  console.log(allCountryData);

  return (
    <>
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllCountryContextProvider>
        <main className={styles.main}>
          <TitleBar />
          <CardContainer data={data} />
        </main>
      </AllCountryContextProvider>
    </>
  );
}
