import Head from "next/head";
import TitleBar from "@/components/titleBar/TitleBar";
import CardContainer from "@/components/cardContainer/CardContainer";
import { createUrl } from "@/functions/createUrl";
import styles from "@/styles/pageStyles/Home.module.scss";
import { useContext, useState } from "react";
import SearchBar from "@/components/searchBar/SearchBar";
import Dropdown from "@/components/dropdown/Dropdown";
import { ThemeContext } from "@/contexts/themeContext";

export const getStaticProps = async () => {
  const url = createUrl("all", {
    fields: ["name", "population", "region", "capital", "flags"],
  });

  const response = await fetch(url);
  const data = await response.json();

  return { props: { data } };
};

export default function Home({ data }) {
  const [theme, setTheme] = useContext(ThemeContext);
  const [filteredRegion, setFilteredRegion] = useState(null);

  return (
    <>
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={theme === "Light" ? "lightMode" : "darkMode"}>
        <TitleBar />
        <div className={styles.formContainer}>
          <SearchBar data={data} />
          <Dropdown data={data} setFilteredRegion={setFilteredRegion} />
        </div>

        <CardContainer data={data} filteredRegion={filteredRegion} />
      </main>
    </>
  );
}
